version: '3.3'
name: tapd-test-network
services:
  # Bitcoin
  bitcoin:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: lightninglabs/bitcoin-core:25
    container_name: bitcoin
    hostname: bitcoin
    cpus: 0.8  # This will limit the service to use at most half of a single CPU
    mem_limit: 8000m  # This will limit the service to use at most 500MB of memory
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli --testnet  --rpcport=18337 --rpcuser=${RPC_USER} --rpcpassword=${RPC_PASSWORD} getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    command: >-
      bitcoind 
      --testnet=1
      --server=1
      --rpcbind=0.0.0.0
      --rpcallowip=0.0.0.0/0
      --rpcport=18337
      --prune=3500 
      --rpcuser=${RPC_USER}
      --rpcpassword=${RPC_PASSWORD}
      --zmqpubrawblock=tcp://0.0.0.0:28336
      --zmqpubrawtx=tcp://0.0.0.0:28337
    restart: no
    expose:
      - '18337'
      - '28336'
      - '28337'
    ports:
      - '18337:18337'
      - '28336:28336'
      - '28337:28337'
    env_file:
      - .env
    volumes:
      - ./volumes/bitcoin/.bitcoin:/home/bitcoin/.bitcoin

  # LND
  alice:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
      LNCLI_RPCSERVER: localhost:10001
      LNCLI_MACAROONPATH: /root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
    stop_grace_period: 2m
    image: lightninglabs/lnd:v0.17.4-beta
    container_name: alice-lnd
    hostname: alice-lnd
    command: >-
      lnd --noseedbackup 
      --trickledelay=5000 
      --alias=${ALIAS}
      --tlsautorefresh
      --tlsextradomain=alice-lnd
      --listen=0.0.0.0:9736 
      --rpclisten=0.0.0.0:10001 
      --restlisten=0.0.0.0:8082
      --rpcmiddleware.enable
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=bitcoind
      --bitcoind.dir=/home/.bitcoin
      --bitcoind.rpchost=bitcoin:18337
      --bitcoind.rpcuser=${RPC_USER}
      --bitcoind.rpcpass=${RPC_PASSWORD}
      --bitcoind.zmqpubrawblock=tcp://bitcoin:28336
      --bitcoind.zmqpubrawtx=tcp://bitcoin:28337
    restart: no
    volumes:
      - ./volumes/lnd/alice:/root/.lnd
      - ./volumes/bitcoin/.bitcoin:/home/.bitcoin
    expose:
      - '8082'
      - '10001'
      - '9736'
    ports:
      - '8082:8082'
      - '10001:10001'
      - '9736:9736'
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "lncli", "getinfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s
    depends_on:
      bitcoin: 
        condition: service_healthy
      
  alice-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    cpus: 0.2  # This will limit the service to use at most half of a single CPU
    mem_limit: 2000m  # This will limit the service to use at most 500MB of memory
    image: lightninglabs/taproot-assets:v0.3.3
    container_name: alice-tap
    hostname: alice-tap
    command: >-
      tapd 
      --network=testnet 
      --debuglevel=debug 
      --tlsextradomain=alice-tap 
      --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 
      --lnd.host=alice-lnd:10001
      --lnd.macaroonpath=/home/tap/.lnd/data/chain/bitcoin/testnet/admin.macaroon
      --lnd.tlspath=/home/tap/.lnd/tls.cert

    restart: no
    volumes:
      - ./volumes/lnd/alice:/home/tap/.lnd
      - ./volumes/tapd/alice-tap:/home/tap/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '8089:8089'
      - '10029:10029'
    healthcheck:
      test: ["CMD", "tapcli", "getinfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s
    depends_on:
      alice:
        condition: service_healthy
      
   # Lightning Terminal
  alice-lit:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    cpus: 0.2  # This will limit the service to use at most half of a single CPU
    mem_limit: 2000m  # This will limit the service to use at most 500MB of memory
    image: lightninglabs/lightning-terminal:v0.12.4-alpha
    container_name: alice-lit
    hostname: alice-lit
    command: >-
      litd 
      --httpslisten=0.0.0.0:8444
      --uipassword=${UIPASSWORD}
      --network=testnet
      --lnd-mode=remote
      --remote.lnd.rpcserver=alice-lnd:10001 
      --remote.lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
      --remote.lnd.tlscertpath=/root/.lnd/tls.cert
      --taproot-assets-mode=remote
      --remote.taproot-assets.rpcserver=alice-tap:10029 
      --remote.taproot-assets.macaroonpath=/root/.tapd/data/testnet/admin.macaroon
      --remote.taproot-assets.tlscertpath=/root/.tapd/tls.cert
      --autopilot.disable
    volumes:
      - ./volumes/lnd/alice:/root/.lnd
      - ./volumes/tapd/alice-tap:/root/.tapd
    restart: no
    expose:
      - '8444'
    ports:
      - '8444:8444'
    env_file:
      - .env
    depends_on:
      alice:
        condition: service_healthy
      alice-tap:
        condition: service_healthy
